# Generated by Django 5.0.1 on 2024-10-30 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_produto_criado_por'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='criado_por',
        ),
    ]
